name: tp1
services:

  gateway:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "gateway"
    container_name: gateway
    entrypoint: /app/gateway
    environment:
      - CLI_SERVER_PORT=5555
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net_tp1

  client:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "client"
    container_name: client
    entrypoint: /app/client
    environment:
      - CLI_SERVER_ADDRESS=gateway:5555
      - CLI_LOG_LEVEL=INFO
      - CLI_DATA_PATH=.data
    volumes:
      - ./.data/games.csv:/app/games.csv
      - ./.data/dataset.csv:/app/dataset.csv
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  genre_filter:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "genre_filter"
    container_name: genre_filter
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
    entrypoint: /app/genre_filter
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  platform_accumulator:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "platform_accumulator"
    container_name: platform_accumulator
    entrypoint: /app/platform_accumulator
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_PEERS_AMOUNT=1
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  platform_counter:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "platform_counter"
    container_name: platform_counter
    entrypoint: /app/platform_counter
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  review_mapper:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "review_mapper"
    container_name: review_mapper
    entrypoint: /app/review_mapper
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  time_played_sorter:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "time_played_sorter"
    container_name: time_played_sorter
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
    entrypoint: /app/time_played_sorter
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner0:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner0
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=0
      - CLI_JOINER_GENRE=Shooter
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

networks:
  testing_net_tp1:
    external: true
    name: testing_net_tp1
