name: system_tp1
services:
  gateway:
    container_name: gateway
    build: ./system/workers/gateway
    networks:
      - testing_net_tp1


networks:
  testing_net_tp1:
    external: true
    name: testing_net_tp1










