name: tp1
services:

  gateway:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "gateway"
    container_name: gateway
    entrypoint: /app/gateway
    environment:
      - CLI_SERVER_PORT=5555
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net_tp1

  client:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "client"
    container_name: client
    entrypoint: /app/client
    environment:
      - CLI_SERVER_ADDRESS=gateway:5555
      - CLI_LOG_LEVEL=INFO
      - CLI_DATA_PATH=.data
    volumes:
      - ./.data/games.csv:/app/games.csv
      - ./.data/dataset.csv:/app/dataset.csv
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  genre_filter:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "genre_filter"
    container_name: genre_filter
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
    entrypoint: /app/genre_filter
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  platform_accumulator:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "platform_accumulator"
    container_name: platform_accumulator
    entrypoint: /app/platform_accumulator
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_PEERS_AMOUNT=1
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  platform_counter:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "platform_counter"
    container_name: platform_counter
    entrypoint: /app/platform_counter
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  review_mapper:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "review_mapper"
    container_name: review_mapper
    entrypoint: /app/review_mapper
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  time_played_sorter:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "time_played_sorter"
    container_name: time_played_sorter
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
    entrypoint: /app/time_played_sorter
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner0:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner0
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=0
      - CLI_JOINER_GENRE=Shooter
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner1:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner1
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=1
      - CLI_JOINER_GENRE=Shooter
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner2:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner2
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=2
      - CLI_JOINER_GENRE=Shooter
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner3:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner3
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=3
      - CLI_JOINER_GENRE=Shooter
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner4:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner4
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=4
      - CLI_JOINER_GENRE=Shooter
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner0-indie:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner0-indie
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=0
      - CLI_JOINER_GENRE=Indie
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner1-indie:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner1-indie
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=1
      - CLI_JOINER_GENRE=Indie
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner2-indie:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner2-indie
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=2
      - CLI_JOINER_GENRE=Indie
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner3-indie:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner3-indie
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=3
      - CLI_JOINER_GENRE=Indie
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  joiner4-indie:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "joiner"
    container_name: joiner4-indie
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_JOINER_ID=4
      - CLI_JOINER_GENRE=Indie
    entrypoint: /app/joiner
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  positive-sorter-0:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "positive_sorter_top_5"
    container_name: positive-sorter-0
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_SORTER_ID=0
      - CLI_TOP=5
    entrypoint: /app/positive_sorter_top_5
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  positive-sorter-1:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "positive_sorter_top_5"
    container_name: positive-sorter-1
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_SORTER_ID=1
      - CLI_TOP=5
    entrypoint: /app/positive_sorter_top_5
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  positive-sorter-2:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "positive_sorter_top_5"
    container_name: positive-sorter-2
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_SORTER_ID=2
      - CLI_TOP=5
    entrypoint: /app/positive_sorter_top_5
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  positive-sorter-3:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "positive_sorter_top_5"
    container_name: positive-sorter-3
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_SORTER_ID=3
      - CLI_TOP=5
    entrypoint: /app/positive_sorter_top_5
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  positive-sorter-4:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "positive_sorter_top_5"
    container_name: positive-sorter-4
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_SORTER_ID=4
      - CLI_TOP=5
    entrypoint: /app/positive_sorter_top_5
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  top-5-aggregator:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "top_5_aggregator"
    container_name: top-5-aggregator
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_SORTERS=5
    entrypoint: /app/top_5_aggregator
    depends_on:
      - gateway
    networks:
      - testing_net_tp1

  5k-reviews-aggregator:
    build:
      context: .
      dockerfile: ./system/Dockerfile
      args:
        WORKER: "5k_reviews_aggregator"
    container_name: 5k-reviews-aggregator
    environment:
      - CLI_SERVER_PORT=5672
      - CLI_LOG_LEVEL=INFO
      - CLI_SORTERS=5
    entrypoint: /app/5k_reviews_aggregator
    depends_on:
      - gateway
    networks:
      - testing_net_tp1



networks:
  testing_net_tp1:
    external: true
    name: testing_net_tp1
